apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: dorian1000/flagger-demo-app:0.0.1
        ports:
        - containerPort: 8888
