apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: initdeployment
  namespace: test
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: initdeployment
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: initdeployment
  service:
    port: 80
    targetPort: 8888
    portDiscovery: true
    portName: http
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    - mesh
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: gateway-error,connect-failure,refused-stream
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  analysis:
    interval: 30s
    maxWeight: 40
    metrics:
    - interval: 30s
      name: request-success-rate
      threshold: 99
    - interval: 30s
      name: request-duration
      threshold: 500
    stepWeight: 20
    threshold: 5
    webhooks:
    - name: load-test
      timeout: 5s
      url: http://flagger-loadtester.test/
      metadata:
        cmd: hey -z 30s -q 10 -c 2 http://initdeployment.test:80/

