apiVersion: apps/v1
kind: Deployment
metadata:
  name: initdeployment
  labels:
    app: initdeployment
spec:
  selector:
    matchLabels:
      app: initdeployment
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
      labels:
        app: initdeployment
    spec:
      containers:
      - name: initdeployment
        image: dorian1000/flagger-demo-app:0.0.1
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP